// Infrastructure layer - SQLite implementations of repositories

pub mod sqlite_analytics_repository;
pub mod sqlite_architectural_decision_repository;
pub mod sqlite_business_rule_repository;
pub mod sqlite_development_phase_repository;
pub mod sqlite_embedding_repository;
pub mod sqlite_framework_repository;
pub mod sqlite_graph_repository;
pub mod sqlite_performance_requirement_repository;
pub mod sqlite_project_repository;
pub mod sqlite_specification_repository;

// Re-export implementations
pub use sqlite_analytics_repository::SqliteAnalyticsRepository;
pub use sqlite_architectural_decision_repository::SqliteArchitecturalDecisionRepository;
pub use sqlite_business_rule_repository::SqliteBusinessRuleRepository;
pub use sqlite_development_phase_repository::SqliteDevelopmentPhaseRepository;
pub use sqlite_embedding_repository::SqliteEmbeddingRepository;
pub use sqlite_framework_repository::SqliteFrameworkRepository;
pub use sqlite_graph_repository::SqliteGraphRepository;
pub use sqlite_performance_requirement_repository::SqlitePerformanceRequirementRepository;
pub use sqlite_project_repository::SqliteProjectRepository;
pub use sqlite_specification_repository::SqliteSpecificationRepository;
